name: Sync Custom Formats from Upstream

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 1:00 AM UTC every day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository and only the master branch
      - name: Checkout master branch only
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history but only for the specified branch
          ref: master  # Specify the branch to checkout

      # Step 2: Set up sparse checkout
      - name: Set up Sparse Checkout
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set metadata.json docs/json/radarr docs/json/sonarr docs/Radarr/Radarr-collection-of-custom-formats.md docs/Sonarr/sonarr-collection-of-custom-formats.md

      # Step 3: Add the upstream repository
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/TRaSH-Guides/Guides.git

      # Step 4: Fetch and Merge Upstream Changes
      - name: Fetch and Merge Upstream Changes
        run: |
          git fetch upstream master
          git merge upstream/master --allow-unrelated-histories

      # Step 5: Push the changes to your forked repository
      - name: Push Changes
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}